### ISSUE TITLE
IPv6-only cluster causes a restart

### ISSUE THREAD

**Issue by hhoover** [fabric8io/fluent-plugin-kubernetes_metadata_filter#158] opened 2018-10-25 17:50 UTC
When using Fluentd in a Kubernetes cluster that is IPv6, the plugin (v 12) can't handle an IPv6 address when connecting to the API server at `https://kubernetes.default.svc.cluster.local`. I've tried setting the `kubernetes_url` to a bracketed IPv6 address but that also results in a restart of Fluentd

Here's the stack trace:
```
2018-10-25 17:44:14 +0000 [error]: unexpected error error_class=SocketError error=#<SocketError: getaddrinfo: Try again>
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `initialize'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `open'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `connect'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/connection.rb:33:in `initialize'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:56:in `new'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:56:in `perform'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:36:in `request'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/kubeclient-1.1.4/lib/kubeclient/watch_stream.rb:18:in `each'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-kubernetes_metadata_filter-1.1.0/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
  2018-10-25 17:44:14 +0000 [error]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-kubernetes_metadata_filter-1.1.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:233:in `block in configure'
2018-10-25 17:44:14 +0000 [info]: shutting down fluentd
2018-10-25 17:44:14 +0000 [info]: shutting down input type="tail" plugin_id="object:2ab97766eff8"
2018-10-25 17:44:14 +0000 [info]: shutting down input type="tail" plugin_id="object:2ab977673314"
2018-10-25 17:44:14 +0000 [error]: unexpected error error="getaddrinfo: Try again"
```

**Comment by richm** [comment] 2018-10-25 18:41
Can you use `curl` from inside the fluentd pod?
Can you write a small ruby script which uses ruby http library directly?  Does it work?

**Comment by hhoover** [comment] 2018-10-25 19:16
curl isn't in the container but irb is!

```
/home/fluent # irb
irb(main):001:0> require "http"
=> true
irb(main):002:0> HTTP.get("https://[fd00:1234::1]:443")
SocketError: getaddrinfo: Try again
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `initialize'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `open'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `connect'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/connection.rb:33:in `initialize'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:56:in `new'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:56:in `perform'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/client.rb:36:in `request'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/chainable.rb:74:in `request'
    from /fluentd/vendor/bundle/ruby/2.4.0/gems/http-0.9.8/lib/http/chainable.rb:18:in `get'
    from (irb):2
    from /usr/bin/irb:11:in `<main>'
irb(main):003:0> quit
```

I'm not fluent (heh heh) in ruby so I hope this is what you were looking for?

**Comment by richm** [comment] 2018-10-25 19:34
Yes, thanks.  So it would appear the problem is in ruby 2.4 and/or http-0.9.8.  Have you tried ruby 2.5?
Is it possible that the container image does not have IPv6 enabled?
What is the os?  `curl` is always installed in rhel/centos/fedora containers.

**Comment by hhoover** [comment] 2018-10-25 19:54
I'm using the fluentd-daemonset off the shelf. The container (fluent/fluentd-kubernetes-daemonset:elasticsearch) uses Alpine Linux.

**Comment by richm** [comment] 2018-10-25 20:02
ok - at any rate, it doesn't appear to be a bug in fluent-plugin-kubernetes_metadata_filter

**Comment by jcantrill** [comment] 2019-01-18 14:11
@trentzhou pull requests are always welcome

**Comment by trentzhou** [comment] 2019-01-22 06:36
OK. I submitted https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/165 
I'm not a sophisticated ruby developer, so please correct me if the change does not work.

**Comment by jcantrill** [comment] 2020-01-02 18:22
@hhoover Does #197 resolve this issue?

**Comment by hhoover** [comment] 2020-01-02 18:48
It should! At the time we moved to filebeat for logging as it supported IPv6. I don't have an IPv6 env to test with currently.

**Comment by stv0g** [comment] 2020-04-22 17:09
I can reproduce this issue even with the fixes of #197. 

As you can see, I am using a API server URL with bracketed IPv6 address.

```
2020-04-22 17:05:33 +0000 [debug]: Kubernetes URL is not set - inspecting environ
2020-04-22 17:05:33 +0000 [debug]: Kubernetes URL is now 'https://[2a00:8a60:6105:201::1]:443/api'
2020-04-22 17:05:33 +0000 [debug]: Found directory with secrets: /var/run/secrets/kubernetes.io/serviceaccount
2020-04-22 17:05:33 +0000 [debug]: Found CA certificate: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
2020-04-22 17:05:33 +0000 [debug]: Found pod token: /var/run/secrets/kubernetes.io/serviceaccount/token
2020-04-22 17:05:33 +0000 [debug]: Creating K8S client
#<Thread:0x0000563b8d87f838@/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:277 run> terminated with exception (report_on_exception is true):
/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:43:in `rescue in set_up_namespace_thread': undefined method `<' for nil:NilClass (NoMethodError)
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:38:in `set_up_namespace_thread'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:277:in `block in configure'
/opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `initialize': failed to connect: getaddrinfo: Name or service not known (HTTP::ConnectionError)
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `open'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `connect'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/connection.rb:43:in `initialize'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:71:in `new'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:71:in `perform'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:31:in `request'
	from /opt/bitnami/fluentd/gems/kubeclient-4.6.0/lib/kubeclient/watch_stream.rb:19:in `each'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:107:in `process_namespace_watcher_notices'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:40:in `set_up_namespace_thread'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:277:in `block in configure'
/opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `open'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `connect'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/connection.rb:43:in `initialize'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:71:in `new'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:71:in `perform'
	from /opt/bitnami/fluentd/gems/http-4.4.1/lib/http/client.rb:31:in `request'
	from /opt/bitnami/fluentd/gems/kubeclient-4.6.0/lib/kubeclient/watch_stream.rb:19:in `each'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:107:in `process_namespace_watcher_notices'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:40:in `set_up_namespace_thread'
	from /opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:277:in `block in configure'
[1, #<Thread:0x0000563b8bfb3340 run>, #<NoMethodError: undefined method `<' for nil:NilClass>, ["/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:43:in `rescue in set_up_namespace_thread'", "/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:38:in `set_up_namespace_thread'", "/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:277:in `block in configure'"]]
[1, #<Thread:0x0000563b8bfb3340 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:17:in `<top (required)>'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:155:in `require'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:155:in `require'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/registry.rb:111:in `search'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/registry.rb:44:in `lookup'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/plugin.rb:155:in `new_impl'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/plugin.rb:109:in `new_output'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:130:in `add_match'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:74:in `block in configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `each'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/bin/fluentd:8:in `<top
(required)>'", "/opt/bitnami/fluentd/bin/fluentd:23:in `load'", "/opt/bitnami/fluentd/bin/fluentd:23:in `<main>'"]]
[1, #<Thread:0x0000563b8bfb3340 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `require'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/registry.rb:111:in `search'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/registry.rb:44:in `lookup'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/plugin.rb:155:in `new_impl'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/plugin.rb:109:in `new_output'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:130:in `add_match'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:74:in `block in configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `each'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'", "/opt/bitnami/fluentd/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'", "/opt/bitnami/fluentd/bin/fluentd:23:in `load'", "/opt/bitnami/fluentd/bin/fluentd:23:in `<main>'"]]
/opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

**Comment by jcantrill** [comment] 2021-01-23 02:52
@anpingli do we have any tests to verify logging with ipv6

**Comment by jcantrill** [comment] 2022-09-30 21:26
Closing due to age

**Closed by jcantrill** 2022-09-30 21:26 UTC
Labels: bug, affects/v0.12, affects/v0.14
