### ISSUE TITLE
Feature Request: docker.container_name in addition to docker.container_id for correlating logs

### ISSUE THREAD

**Issue by mumoshu** [fabric8io/fluent-plugin-kubernetes_metadata_filter#100] opened 2017-12-01 11:52 UTC
Hi, thanks for maintaining the great project 👍 

I'm using dd-agent + Datadog to collect metrics from my pods and containers.
It annotates metrics with the container name like "k8s_<deployment/daemonset name>_<pod name>_<...>` which is the container name shown when we run `docker ps`, but not container "id".

What makes it relevant to this project is the recent arrival of [Datadog Log Management](https://www.datadoghq.com/blog/announcing-logs/).
It allows annotating logs with arbitrary metadata - and I have been utilizing this kubernetes_metadata_filter in combination with [fluent-plugin-datadog-log](https://github.com/mumoshu/fluent-plugin-datadog-log) to annotate logs as similar as possible to how dd-agent annotates metrics.

Right now, only a important difference between annotated metadata between metrics and logs are docker container's id and docker container's name. I'd like to rely on container name  rather than id because it looks a bit friendlier for human readers.

// Beware it isn't `kubernetes.container_name` which is specified via `containers[].name` in your pod spec.

Would it be ok to add the following features to support this use-case?

- An option to include/exlude `docker.container_id`
   - When one relies on container name for correlation, container id is unnecessary
   - Perhaps `include_docker_container_id` which is `true` by default?
- An option to include `docker.container_name`(NEW)
  - Perhaps `include_docker_container_name` which is `false` by default?

I can send a pull request if this feature request is acceptable.
Thanks!

**Comment by jcantrill** [comment] 2017-12-04 00:10
Submit a PR  for your use case and be advised there are some changes #93 is introducing to refactor caching and make the code less monolithic

**Comment by jcantrill** [comment] 2018-05-17 16:45
Is this a duplicate of #54 and resolved by #112

**Comment by jcantrill** [comment] 2021-01-23 03:11
Closing as resolved

**Closed by jcantrill** 2021-01-23 03:11 UTC
Labels: enhancement
