### ISSUE TITLE
kubernetes_metadata plugin initial pull and cache strategy issue

### ISSUE THREAD

**Issue by qingling128** [fabric8io/fluent-plugin-kubernetes_metadata_filter#187] opened 2019-09-17 19:30 UTC
Hi,

Recently we noticed some intriguing behavior based on apiserver logs that raised some performance concern:

The `kubernetes_metadata` plugin at startup lists all pods **with no filter** which caused load pressure on etcd for large clusters. After startup (even though it looks like a watch has been set up), it queries the API for certain pods every minute.

Looking at the code, it looks like what the kubernetes_metadata plugin intends to do is:
1. Initially queries API to get all pods and the resource version. (The initial pull **has no filters**. Besides that, it **does not seem to add these results to cache**.)
    Related code: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/8a75c3d5811b6970ef7d11a42c43a74d3902b839/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L28
2. Sets up a pod watch with that resource version and keeps updating the cache.
    Related code: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/8a75c3d5811b6970ef7d11a42c43a74d3902b839/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L29
3. Only queries API again with pod name filter if the pod is not already in the cache. (In theory this should be rare, which contradicts what we saw from the log: The plugin queries the API every minute. Perhaps this is because we did not cache the results in step 1?)
    Related code: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/f1831d66baeee3540ca737e42b009d43c0513878/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb#L29

**Proposal**

1. In the initial "get_pods", filter by local nodes. (I noticed that in the README, it says this plugin also supports `multi-tenant`. I'm not sure if filtering by local nodes would affect that feature).
2. Cache the `get_pods` results from the initial poll. (Unless I read the code wrong, it does not seem to cache it).

**Our configuration**

```
    <filter reform.**>
      @type kubernetes_metadata
      # Interval in seconds to dump cache stats locally in the Fluentd log.
      stats_interval 300
      # TTL in seconds of each cached element.
      cache_ttl 30
      # Skip fetching unused metadata.
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>
```

**Impact**

Load pressure on etcd + Fluentd OOM crash loops for large clusters in the initial pull.

**Comment by richm** [comment] 2019-09-17 19:35
Looks like this issue might be similar to, or a duplicate of, https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/179 or https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/170

**Comment by qingling128** [comment] 2019-09-17 20:01
Yeah, that looks similar. Do we intend to cache the `get_pods` results after the initial pull? I wonder if it's by designed not cached or an oversight.

**Comment by richm** [comment] 2019-09-17 20:19
> Yeah, that looks similar. Do we intend to cache the `get_pods` results after the initial pull? I wonder if it's by designed not cached or an oversight.

I don't know.  Likely we just never noticed it was a problem in our use in OpenShift, just like we never noticed the rescan every minute, nor the memory problem.  That is, the plugin Just Works for us with our current usage.

However, patches are welcome, as we (openshift logging team) are not likely to work on these items unless they begin to affect us.

I'm assuming you would want the initial search:
```ruby
resource_version = @client.get_pods.resourceVersion
```
to both 1) search only for the pods on the current node and 2) cache the result.

Similarly to the other api calls - they should only query the pods/namespaces which are on the node.  We recently upgraded the plugin to use kubeclient 4.4 - that might provide a better way to query by specific pods/namespaces on specific nodes.

I'm not sure why the api is doing a search every minute - that might be another bug which needs to be addressed.

**Comment by qingling128** [comment] 2019-09-17 20:40
@richm - Thanks for the info! That makes sense. We're still evaluating the impact of this issue and its priority. We might contribute a patch.

**Comment by jkohen** [comment] 2019-09-24 18:56
I'm working on a fix. @jkohen

**Closed** 2019-09-27 16:20 UTC
